# general settings
name: LKDN-S_C42_A42_adam_ema_x4_DF2K_from_scratch_950k
model_type: SRModel
scale: 4
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    # dataroot_gt: datasets/DF2K/DF2K_train_HR_sub
    # dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic/X4_sub
    # meta_info_file: basicsr/data/meta_info/meta_info_DF2K3450sub_GT.txt
    # (for lmdb)
    dataroot_gt: datasets/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic_X4_sub.lmdb

    io_backend:
      # type: disk
      # (for lmdb)
      type: lmdb

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: DIV2K_val
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_valid_HR
    dataroot_lq: datasets/DIV2K/DIV2K_valid_LR_bicubic/X4
    filename_tmpl: '{x4}'
    io_backend:
      type: disk

# network structures
network_g:
  type: LKDN_S
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 42
  num_atten: 42
  num_block: 5
  upscale: 4
  num_in: 4
  conv: BSConvU_rep
  upsampler: pixelshuffle_rep

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam  # Adam has a slightly better effect in the later stage
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

    # type: Adan
    # lr: !!float 5e-3
    # betas: [0.98, 0.92, 0.99]
    # weight_decay: 0
    # foreach: true

  scheduler:
    type: MultiStepLR
    milestones: [950000]
    gamma: 0.5

  total_iter: 950000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500